name: Release

on:
  push:
    branches:
      - main
jobs:
  build:
    if:
      github.actor != 'carbon-bot'
      &&	!contains(github.event.head_commit.message, 'ci-skip')
    name: Create release - Node.js v18.16.1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18.16.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile

      - name: Initialize Git user
        run: |
          git config --global user.name "David Bradshaw"
          git config --global user.email "david.bradshaw@ibm.com"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Github & NPM 🚀
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
          yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DCO_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
